### ISSUE TITLE
LyncPresenceBridge.exe wont run

### ISSUE THREAD

**Issue by VincentK16** [uCtrlDev/Lync-presence-bridge#5]
Hi,

Everytime when I launched the LyncPresenceBridge.exe, there will be a window pop up showing the program stop running. I can only change the colour of LED manually through the icon only not linked with Skype. I am using normal Skype. 

Thanks.

**Comment by thomasjsn** [comment]
Hey, it only connects to Skype for Business (previously Lync). That is why you are seeing that message.

Not sure what libraries are available for getting the presence status of regular Skype.

**Comment by VincentK16** [comment]
Thanks for confirming.

Warmest regards,
Vincent Kok

Sent from my iPad

On Jan 4, 2017, at 22:55, Thomas Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey, it only connects to Skype for Business (previously Lync). That is why you are seeing that message.

Not sure what libraries are available for getting the presence status of regular Skype.

-
